### PR TITLE
Removing image tag

### PR DESCRIPTION
**Pull request by Borales**

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
I swear I added this one, oh well.

Cheers :+1:

Will investigate the failing tests and then probably do some cleanup of tests and release a 0.4.0 within the next day or two.

**Comment by Borales** [comment]
@RyanTheAllmighty Great, thanks! I'll be waiting :)

**Comment by RyanTheAllmighty** [comment]
@Borales I've just pushed out 0.4.0 to NPM, no idea how long NPM takes to start distributing those changes though

**Comment by Borales** [comment]
@RyanTheAllmighty it's already there, thank you for a quick check!
I will do another PR for README as well

**Pull request merged**
